### PR TITLE
Improve Auth README 

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by danielpassos** [comment]
@corinnekrych 👀 ?

**Comment by danielpassos** [comment]
@corinnekrych 👀 ?

**Comment by corinnekrych** [comment]
👁 👃 👁

**Comment by corinnekrych** [comment]
@danielpassos PR worth a thousand words: https://github.com/danielpassos/aerogear-backend-cookbook/pull/1

**Comment by danielpassos** [comment]
@corinnekrych Done!

**Comment by corinnekrych** [comment]
+1

**Pull request merged**
