### PR TITLE
Change the default expiration time from KC

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Comment by corinnekrych** [comment]
@abstractj do you really want the access token to expire after 30 seconds?
and the refresh token to expired in 2mins (requiring entering login/grant again)?
I usually set it to that low to test refresh token...
Not sure if nice for demo.
Maybe we should explicitly set them but make them longer and document how to shorten them to test refresh.

wdyt?

**Comment by danielpassos** [comment]
@abstractj Why did you added it? Only to make it explicit?

**Comment by abstractj** [comment]
@corinnekrych the point of this PR, to make people test what you've done with refresh tokens. Also, I don't see any problems on it.

@danielpassos nope, to change the defaults.

**Comment by matzew** [comment]
should we have a note on the README about the changes, the override of the default values?

**Comment by abstractj** [comment]
@matzew not sure why, the explanation of KC parameters is available at their documentation.

**Comment by matzew** [comment]
sure, but if our demo overrides those defaults it would be nice to mention
that

On Wednesday, February 25, 2015, Bruno Oliveira <notifications@github.com>
wrote:

> @matzew <https://github.com/matzew> not sure why, the explanation of KC
> parameters is available at their documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-backend-cookbook/pull/20#issuecomment-76050722>
> .
>


-- 
Sent from Gmail Mobile

**Comment by abstractj** [comment]
@matzew never mind, I'm closing this PR. The several cons, made me wish to leave it as is.

**Pull request closed without merging**
