### PR TITLE
TOTP & Brute force detection

### PR DESCRIPTION
**Pull request by abstractj**
Aloha, this PR adds two features from Keycloak:
- TOTP by default to our current user
- Brute force detection already enabled

To test it, just try to import the json file as a realm on Keycloak and login again.

### CODE REVIEW

**Comment by edewit** [comment]
why would we add totp to the shoot and share demo?

**Comment by corinnekrych** [comment]
@abstractj as @edewit did a separate folder OTP-Demo with its own realm file in this PR: https://github.com/aerogear/aerogear-backend-cookbook/pull/24
I think it would make sense to add the TOTP feature in that realm rather that shoot-realm. 
@abstractj Do you mind to apply those on the new realm?

**Comment by abstractj** [comment]
@edewit to have a single demo for OTP and OAuth2

**Comment by abstractj** [comment]
@corinnekrych I understand, why not a single demo for everything?

**Comment by corinnekrych** [comment]
@abstractj short answer: keep it simple.
longer one:
The approach taken in the cookbook is "one simple demo does one simple thing". This si what we do on all client cookbook demo:
- one demo for oauth2
- one demo for otp etc...
let's keep it simple and consistent with client cookbook.
Besides changes is already merged.

**Comment by abstractj** [comment]
@corinnekrych I really can't any simplicity here, once you have to import 2 realms to run the demos

**Comment by edewit** [comment]
If you combine the 2 backends, it means to run and test oauth2 I'll have to install the OTP demo as well and switch between the to making the process hard + you might only be interested in oath2

**Comment by abstractj** [comment]
@edewit @corinnekrych let's do into this way. I'm closing this PR and will open a new one when we focus on OTP stuff.

Thanks for the input.

**Pull request closed without merging**
